web:
  build: nginx
  links: 
    - golem
    - giant
  volumes:
      - ./nginx/nginxconf:/etc/nginx/sites-enabled
  ports:
    - "80:80"
  restart: always
  mem_limit: 500000000
golem:
  build: golem
  volumes:
    - ./golem:/app
  links:
    - db
    - redis
  ports:
    - "8801:8091"
  restart: always
  mem_limit: 2000000000
  environment:
    - LANG=C.UTF-8
giant:
  build: giant
  volumes:
    - ./giant:/app
  links: 
    - db
    - redis
  ports:
    - "8800:8091"
  restart: always
  mem_limit: 2000000000
  environment:
    - LANG=C.UTF-8
db:
  image: snakeliwei/alpine-postgresql:9.5
  ports:
    - "5432:5432"
  restart: always
  mem_limit: 1000000000
  volumes:
    - ./db/data:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=bestone
    - POSTGRES_PASSWORD=q4V*t5YWwRtq92G&^nRDQE34
redis:
  image: microbox/redis:2.8.19 
  ports: 
    - "6379:6379"
  volumes:
    - ./redis/data:/data
  restart: always
  mem_limit: 1000000000

